# Generated by Django 3.2.5 on 2021-10-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_alter_sanpham_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donhang',
            name='masp',
        ),
        migrations.RemoveField(
            model_name='donhang',
            name='soluongban',
        ),
        migrations.RemoveField(
            model_name='sanpham',
            name='hinhanh',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
