# Generated by Django 3.2.5 on 2021-10-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0009_auto_20211027_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sanpham',
            name='stock',
            field=models.CharField(max_length=255),
        ),
    ]
