# Generated by Django 3.2.5 on 2021-11-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0013_sanphamthuocdonhang'),
    ]

    operations = [
        migrations.AddField(
            model_name='sanpham',
            name='noibat',
            field=models.BooleanField(default=False),
        ),
    ]
